#!/usr/bin/env bash
# This script displays the content of the current directory in a list format

file_path = "school"

if [ -e $file_path ]
then
    echo "school file exists"
    if [ -s $file_path ]
    then
        echo "school file is not empty"
        if [ -f $file_path ]
        then
            echo "school is a regular file"
        else
            echo "(nothing)"
        fi
    else
        echo "school file is empty"
    fi
else
    echo "school file does not exist"
fi
