#!/usr/bin/env bash
# This script displays the content of the current directory in a list format

filename = "school"

if [ -e $filename ]
then
    echo "$filename file exists"
    if [ -s $filename ]
    then
        echo "$filename file is not empty"
        if [ -f $filename ]
        then
            echo "$filename is a regular file"
        else
            echo "(nothing)"
        fi
    else
        echo "$filename file is empty"
    fi
else
    echo "$filename file does not exist"
fi
