#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with this requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1\tlocalhost/127.0.0.2\tlocalhost/' ~/hosts.new
sed -i '2i8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
